[package]
name = "pngyinx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
codegen-units = 1
opt-level = "z"
strip = "symbols"
lto = "fat"

[dependencies]
crc32fast = "1.4.0"
clap = "4.5.1"